version: '3'
services:
  webserver:
    build: .
    restart: always
    expose:
      - "8080"
    labels:
      - "traefik.http.routers.webserver.rule=PathPrefix(`/`)"
    deploy:
      replicas: 11

  loadbalancer:
    image: "traefik:2.1"
    command:
      - "--providers.docker=true"
      - "--entrypoints.web.address=:8080"
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
